Generate a typed TypeScript client (OpenAI default target):

  $ promptc codegen researcher.prompt | head -3
  // Generated by promptc — do not edit.
  export type ResearcherInputs = Record<string, never>;
  export type ResearcherOutput = { ticker: string; rating: "buy" | "hold" | "sell"; summary: string };

Codegen for a bad target is a usage error:

  $ promptc codegen researcher.prompt --target bogus >out 2>&1; code=$?; tr -d "'" < out | sed -n '/^promptc: option /,/^[[:space:]]*anthropic or gemini$/p'; echo "[$code]"
  promptc: option --target: invalid value bogus, expected one of openai,
           anthropic or gemini
  [124]
